components:
    schemas:
        Foo:
            properties:
                description:
                    type: string
                id:
                    format: int64
                    type: integer
                name:
                    type: string
            type: object
        Goo:
            properties:
                description:
                    type: string
                fooId:
                    format: int64
                    type: integer
                id:
                    format: int64
                    type: integer
                name:
                    type: string
info:
    description:
        ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless R3B2"
    version: v1.0
openapi: 3.0.1
paths:
    "/foo":
        get:
            operationId: getFooPage
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Foo"
                                type: array
            tags: ["Foo"]
        post:
            operationId: postFoo
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
            tags: ["Foo"]
    "/foo/{fooId}":
        delete:
            operationId: deleteFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
            tags: ["Foo"]
        get:
            operationId: getFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
            tags: ["Foo"]
        patch:
            operationId: patchFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
            tags: ["Foo"]
        put:
            operationId: putFoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Foo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Foo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Foo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Foo"
            tags: ["Foo"]
    "/foo/{fooId}/goos":
        get:
            operationId: getFooGoosPage
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Goo"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Goo"
                                type: array
            tags: ["Goo"]
        post:
            operationId: postFooGoo
            parameters:
                - in: path
                  name: fooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
            tags: ["Goo"]
    "/goo/{gooId}":
        delete:
            operationId: deleteGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
            tags: ["Goo"]
        get:
            operationId: getGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
            tags: ["Goo"]
        patch:
            operationId: patchGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
            tags: ["Goo"]
        put:
            operationId: putGoo
            parameters:
                - in: path
                  name: gooId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Goo"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Goo"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Goo"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Goo"
            tags: ["Goo"]